version: '3.7'

networks:
  postgres:

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: athenify
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - postgres

volumes:
  postgres_data: