version: '3.7'

networks:
  athenify:

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: athenify
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - athenify
    
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - athenify

volumes:
  postgres_data:
  redis_data: